module.exports = [
  {
    title: "Olive Lounge",
    bio: "Mid-century lounge in olive velvet with a honey teak frame.",
    category: "interior",
    imageUrl: "designs/olive-lounge.webp",
    source: "curated",
    featured: true,
    price: 640,
    currency: "EUR",
  },
  {
    title: "Jasmine Teak Chair",
    bio: "Sculptural teak and walnut chair with a sweeping back leg.",
    category: "modern",
    imageUrl: "designs/jasmine-teak-chair.webp",
    source: "curated",
    featured: true,
    price: 420,
    currency: "EUR",
  },
  {
    title: "Void Origami Chair",
    bio: "Bentwood lounge with mustard lining and built-in book pockets.",
    category: "modern",
    imageUrl: "designs/void-origami-chair.webp",
    source: "curated",
    featured: true,
    price: 380,
    currency: "EUR",
  },
  {
    title: "Mobius Walnut Chair",
    bio: "Solid walnut sculpture with a continuous seat-to-leg curve.",
    category: "minimal",
    imageUrl: "designs/mobius-walnut.webp",
    source: "curated",
    featured: true,
    price: 520,
    currency: "EUR",
  },
  {
    title: "MS22 Triplex",
    bio: "Organic tripod chair in dark grain, carved as one volume.",
    category: "minimal",
    imageUrl: "designs/ms22-triplex.webp",
    source: "curated",
    featured: true,
    price: 490,
    currency: "EUR",
  },
  {
    title: "Cream Walnut Lounge",
    bio: "Fluid walnut frame with stacked cream cushions.",
    category: "interior",
    imageUrl: "designs/cream-walnut-lounge.webp",
    source: "curated",
    featured: true,
    price: 450,
    currency: "EUR",
  },
  {
    title: "Stacking Sculpture Chairs",
    bio: "Japanese woodwork chairs that slide and stack as sculpture.",
    category: "furniture",
    imageUrl: "designs/stacking-chairs.webp",
    source: "curated",
    featured: true,
    price: 560,
    currency: "EUR",
  },
  {
    title: "Void Cone Chair",
    bio: "Futuristic cone seat on architectural white supports.",
    category: "futuristic",
    imageUrl: "designs/void-cone.webp",
    source: "curated",
    featured: true,
    price: 710,
    currency: "EUR",
  },
  {
    title: "Concept Sketch Set",
    bio: "Five studio studies: office, lounge, table, faceted chair and daybed.",
    category: "furniture",
    imageUrl: "designs/concept-sketches.webp",
    source: "curated",
    featured: true,
    price: 95,
    currency: "EUR",
  },
  {
    title: "Chair Studies",
    bio: "Technical sketches of swivel, cantilever and organic lounge chairs.",
    category: "furniture",
    imageUrl: "designs/chair-studies.webp",
    source: "curated",
    featured: true,
    price: 85,
    currency: "EUR",
  },
];
